### ISSUE TITLE
Open Street Map problem

### ISSUE THREAD

**Issue by walid0912** [lotfiferaga/SIG_Explore#2]
the OSMNX library does not give the full detailed data on elevation which is important in this case :)

**Comment by lotfiferaga** [comment]
OSMNX is the only available free API library that provides small portion of data even tho it is not enough to calculate certain stuff but still enough to display SIG data on tree maps and 3D graphs :/

**Comment by walid0912** [comment]
well enough said and done

**Comment by lotfiferaga** [comment]
yes but there's other APIs that require keys

**Comment by walid0912** [comment]
all good thx
